import { useState } from 'react';
import { FaArrowRight, FaArrowLeft } from 'react-icons/fa';

export default function Calendar() {
  const today = new Date();
  const [currentMonth, setCurrentMonth] = useState(today.getMonth());
  const [currentYear, setCurrentYear] = useState(today.getFullYear());

  const monthNames = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ];

  // Get the first day of the month (0 = Sunday, 6 = Saturday)
  const firstDayOfMonth = new Date(currentYear, currentMonth, 1).getDay();
  // Get total days in the month
  const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();

  // Generate an array with empty slots for alignment + days
  const calendarDays = [
    ...Array(firstDayOfMonth).fill(''),
    ...Array.from({ length: daysInMonth }, (_, i) => i + 1),
  ];

  const handlePrevMonth = () => {
    if (currentMonth === 0) {
      setCurrentMonth(11);
      setCurrentYear(currentYear - 1);
    } else {
      setCurrentMonth(currentMonth - 1);
    }
  };

  const handleNextMonth = () => {
    if (currentMonth === 11) {
      setCurrentMonth(0);
      setCurrentYear(currentYear + 1);
    } else {
      setCurrentMonth(currentMonth + 1);
    }
  };

  return (
    <div className="max-w-sm mx-auto p-4 rounded-lg">
      <div className="flex justify-between items-center mb-4">
        <button
          onClick={handlePrevMonth}
          className="text-gray-500 hover:text-gray-700 hover:cursor-pointer"
          title="Left arrow"
        >
          <FaArrowLeft />
        </button>
        <h2 className="text-lg font-semibold">
          {monthNames[currentMonth]} {currentYear}
        </h2>
        <button
          onClick={handleNextMonth}
          className="text-gray-500 hover:text-gray-700 hover:cursor-pointer"
          title="Right arrow"
        >
          <FaArrowRight />
        </button>
      </div>
      <div className="grid grid-cols-7 text-center text-gray-500 font-medium mb-2">
        <div>Sun</div>
        <div>Mon</div>
        <div>Tue</div>
        <div>Wed</div>
        <div>Thu</div>
        <div>Fri</div>
        <div>Sat</div>
      </div>
      <div className="grid grid-cols-7 text-center gap-1">
        {calendarDays.map((day, idx) => {
          const isToday =
            day === today.getDate() &&
            currentMonth === today.getMonth() &&
            currentYear === today.getFullYear();

          return (
            <div
              key={idx}
              className={`p-2 rounded-full ${
                isToday ? 'bg-blue-500 text-white' : ''
              }`}
            >
              {day}
            </div>
          );
        })}
      </div>
    </div>
  );
}

// Calendar code was generated by ChatGPT
